meg/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('sites.urls')),
    path('sites/', include('sites.urls')),
    path('summary/', include('summary.urls')),
    path('summary-average/', include('summary.urls')),
    path('admin/', admin.site.urls),
]

sites/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:site_id>/', views.detail, name='detail'),
]

summary/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

sites/models.py
from django.db import models
from django.db.models import Sum

# Create your models here.

class Site(models.Model):
	name = models.CharField('name of site', max_length=200)
	def __str__(self):
		return self.name
	@staticmethod
	def sum_by_site():
    		return Site.objects.annotate(A_value=Sum('visit__A_value')).annotate(B_value=Sum('visit__B_value'))
	@staticmethod
	def avg_by_site():
		return Site.objects.raw('select s.id, name, round(avg(A_value),2) as A_value, round(avg(B_value),2) as B_value from sites_site s inner join sites_visit sv on sv.site_id_id=s.id group by s.id order by s.id;')

class Visit(models.Model):
	site_id = models.ForeignKey(Site, on_delete=models.CASCADE)
	when = models.DateField('date site visited')
	A_value = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
	B_value = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

summary/models.py
from django.db import models

# Create your models here.

sites/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render

from .models import Site


def index(request):
    sites_list=Site.objects.all()
    context = {
        'sites_list': sites_list,
    }
    return HttpResponse(render(request, 'sites/index.html', context))

def detail(request, site_id):
    try:
        site = Site.objects.get(pk=site_id)
    except Site.DoesNotExist:
        raise Http404("Site does not exist")
    return render(request, 'sites/detail.html', {'site': site })

summary/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render

from sites.models import Site


def index(request):
    if request.path=='/summary-average/':
        sites_list=Site.avg_by_site()
    else:
        sites_list=Site.sum_by_site()
    context = {'sites_list': sites_list}
    return HttpResponse(render(request, 'summary/index.html', context))

sites/templates/sites/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>3MW - Application Task</title>
    <meta name="viewport" content="width=520, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

</head>
<body>

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active" role="presentation" >
                        <a href="/sites">Sites</a>
                </li>
                <li role="presentation" >
                        <a href="/summary">Summary</a>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
      </nav>

    <div class="container">
<h1>Site Details - {{ site.name }}</h1>

        <table class="table">
            <thead>
                <tr><td><strong>Date</strong></td>
                <td><strong>A Value</strong></td>
                <td><strong>B Value</strong></td></tr>
            </thead>
            
{% for visit in site.visit_set.all %}   
                <tr>
                    <td>{{ visit.when }}</td>
                    <td>{{ visit.A_value }}</td>
                    <td>{{ visit.B_value }}</td>
                </tr>
{% endfor %}            
        </table>
</body>
</html>

sites/templates/sites/index.html
<!DOCTYPE html>
<html>
<head>
    <title>3MW - Application Task</title>
    <meta name="viewport" content="width=520, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

</head>
<body>

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active" role="presentation" >
                        <a href="/sites">Sites</a>
                </li>
                <li role="presentation" >
                        <a href="/summary">Summary</a>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
      </nav>



    <div class="container">
        <h1>Sites</h1>

{% if sites_list %}
    <ul class="list-group">
    {% for site in sites_list %}
        <li class="list-group-item"><a href="/sites/{{ site.id }}/">{{ site.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No sites are available.</p>
{% endif %}

   </div>


</body>
</html>

summary/templates/summary/average.html
<!DOCTYPE html>
<html>
<head>
    <title>3MW - Application Task</title>
    <meta name="viewport" content="width=520, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

</head>
<body>

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li role="presentation" >
                        <a href="/sites">Sites</a>
                </li>
                <li class="active" role="presentation" >
                        <a href="/summary">Summary</a>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
      </nav>



    <div class="container">
        <h1>Summary</h1>

          <a href="/summary"><button type="button" class="btn btn-primary">Sum</button></a>
          <a href="/summary-average"><button type="button" class="btn btn-primary active">Average</button></a>

        <table class="table">
            <thead>
                <tr>
                    <td><strong>Site</strong></td>
                    <td><strong>A Value</strong></td><td><strong>B Value</strong></td>
                </tr>
            </thead>

{% if sites_list %}
{% for site in sites_list %}
                <tr>
                    <td>{{ site.name }}</td>
                    <td>{{ site.A_value }}</td>
                    <td>{{ site.B_value }}</td>
                </tr>
{% endfor %}
{% else %}
  <p>No sites are available.</p>
{% endif %}
                <tr>
                    <td>ABC Site</td>
                    <td>5.00</td>
                    <td>15.00</td>
                </tr>
            
                <tr>
                    <td>XYZ Site</td>
                    <td>5.00</td>
                    <td>15.00</td>
                </tr>
            
        </table>
    </div>


</body>
</html>

summary/templates/summary/index.html
<!DOCTYPE html>
<html>
<head>
    <title>3MW - Application Task</title>
    <meta name="viewport" content="width=520, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

</head>
<body>

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li role="presentation" >
                        <a href="/sites">Sites</a>
                </li>
                <li class="active" role="presentation" >
                        <a href="/summary">Summary</a>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
      </nav>



    <div class="container">
        <h1>Summary</h1>

          <a href="/summary"><button type="button" class="btn btn-primary {% if request.path == '/summary/' %}active{% endif %}">Sum</button></a>
          <a href="/summary-average"><button type="button" class="btn btn-primary {% if request.path == '/summary-average/' %}active{% endif %}">Average</button></a>



        <table class="table">
            <thead>
                <tr>
                    <td><strong>Site</strong></td>
                    <td><strong>A Value</strong></td><td><strong>B Value</strong></td>
                </tr>
            </thead>
            
{% if sites_list %}
{% for site in sites_list %}
                <tr>
                    <td>{{ site.name }}</td>
                    <td>{{ site.A_value }}</td>
                    <td>{{ site.B_value }}</td>
                </tr>
{% endfor %}
{% else %}
  <p>No sites are available.</p>
{% endif %}
            
        </table>
    </div>


</body>
</html>